### ISSUE TITLE
Bootloader error installing 4.0.0 Driver on Jetson Nano

### ISSUE THREAD

**Issue by aidanwhelan** [alliedvision/linux_nvidia_jetson#47]
I'm hoping to use the newly-released 4.0.0 driver on my Jetson Nano Production Module running JetPack 4.6.1 and L4T version 32.7.1, however running the installation script from the precompiled tarball gives the following output:   
```
Allied Vision MIPI CSI-2 camera driver for NVidia Jetson (kernel 4.9.253)
Install kernel driver (y/n)? y


Installing...
Extracting repository:
Release.gpg
KEY.gpg
Release
Packages
avt-nvidia-l4t-kernel_4.9.253-
tegra-32.7.1-4.0.0~gc3fa7ac49_arm64.deb
avt-nvidia-l4t-kernel-dtbs_4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49_arm64.deb
avt-nvidia-l4t-kernel-headers_4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49_arm64.deb
avt-nvidia-l4t-bootloader_32.7.1-4.0.0~gc3fa7ac49_arm64.deb
Importing Repository:
OK
deb file:/opt/avt/packages ./
Get:1 file:/opt/avt/packages ./ InRelease
Ign:1 file:/opt/avt/packages ./ InRelease
Get:2 file:/opt/avt/packages ./ Release [816 B]
Get:2 file:/opt/avt/packages ./ Release [816 B]
Get:3 file:/opt/avt/packages ./ Release.gpg [691 B]
Get:3 file:/opt/avt/packages ./ Release.gpg [691 B]
Get:4 file:/opt/avt/packages ./ Packages [3,711 B]                                                    
Hit:5 https://repo.download.nvidia.com/jetson/common r32.7 InRelease                                  
Hit:6 http://ports.ubuntu.com/ubuntu-ports bionic InRelease                                          
Hit:7 https://repo.download.nvidia.com/jetson/t210 r32.7 InRelease                                    
Hit:8 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease                  
Hit:9 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease            
Hit:10 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease            
Reading package lists... Done                      
Installing packages:
Reading package lists... Done
Building dependency tree      
Reading state information... Done
The following packages were automatically installed and are no longer required:
  apt-clone archdetect-deb bogl-bterm busybox-static cryptsetup-bin dpkg-repack
  gir1.2-timezonemap-1.0 gir1.2-xkl-1.0 grub-common kde-window-manager kinit kio kpackagetool5
  kwayland-data kwin-common kwin-data kwin-x11 libdebian-installer4 libkdecorations2-5v5
  libkdecorations2private5v5 libkf5activities5 libkf5attica5 libkf5completion-data libkf5completion5
  libkf5declarative-data libkf5declarative5 libkf5doctools5 libkf5globalaccel-data libkf5globalaccel5
  libkf5globalaccelprivate5 libkf5idletime5 libkf5jobwidgets-data libkf5jobwidgets5
  libkf5kcmutils-data libkf5kcmutils5 libkf5kiocore5 libkf5kiontlm5 libkf5kiowidgets5
  libkf5newstuff-data libkf5newstuff5 libkf5newstuffcore5 libkf5package-data libkf5package5
  libkf5plasma5 libkf5quickaddons5 libkf5solid5 libkf5solid5-data libkf5sonnet5-data
  libkf5sonnetcore5 libkf5sonnetui5 libkf5textwidgets-data libkf5textwidgets5 libkf5waylandclient5
  libkf5waylandserver5 libkf5xmlgui-bin libkf5xmlgui-data libkf5xmlgui5 libkscreenlocker5
  libkwin4-effect-builtins1 libkwineffects11 libkwinglutils11 libkwinxrenderutils11 libqgsttools-p1
  libqt5designer5 libqt5help5 libqt5multimedia5 libqt5multimedia5-plugins libqt5multimediaquick-p5
  libqt5multimediawidgets5 libqt5opengl5 libqt5quickwidgets5 libqt5sql5 libqt5test5 libxcb-composite0
  libxcb-cursor0 libxcb-damage0 os-prober python3-dbus.mainloop.pyqt5 python3-icu python3-pam
  python3-pyqt5 python3-pyqt5.qtsvg python3-pyqt5.qtwebkit qml-module-org-kde-kquickcontrolsaddons
  qml-module-qtmultimedia qml-module-qtquick2 rdate tasksel tasksel-data
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  nvidia-l4t-initrd nvidia-l4t-tools nvidia-l4t-xusb-firmware
The following packages will be REMOVED:
  nvidia-l4t-bootloader nvidia-l4t-jetson-io nvidia-l4t-kernel nvidia-l4t-kernel-dtbs
  nvidia-l4t-kernel-headers
The following NEW packages will be installed:
  avt-nvidia-l4t-bootloader avt-nvidia-l4t-kernel avt-nvidia-l4t-kernel-dtbs
  avt-nvidia-l4t-kernel-headers
The following packages will be upgraded:
  nvidia-l4t-initrd nvidia-l4t-tools nvidia-l4t-xusb-firmware
3 upgraded, 4 newly installed, 5 to remove and 188 not upgraded.
Need to get 7,448 kB/36.5 MB of archives.
After this operation, 2,322 kB disk space will be freed.
Get:1 file:/opt/avt/packages ./ avt-nvidia-l4t-bootloader 32.7.1-4.0.0~gc3fa7ac49 [736 kB]
Get:2 https://repo.download.nvidia.com/jetson/t210 r32.7/main arm64 nvidia-l4t-initrd arm64 32.7.2-20220420143418 [7,169 kB]
Get:3 file:/opt/avt/packages ./ avt-nvidia-l4t-kernel 4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49 [20.0 MB]
Get:4 file:/opt/avt/packages ./ avt-nvidia-l4t-kernel-dtbs 4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49 [123 kB]
Get:5 https://repo.download.nvidia.com/jetson/t210 r32.7/main arm64 nvidia-l4t-xusb-firmware arm64 32.7.2-20220420143418 [87.7 kB]
Get:6 https://repo.download.nvidia.com/jetson/t210 r32.7/main arm64 nvidia-l4t-tools arm64 32.7.2-20220420143418 [191 kB]
Get:7 file:/opt/avt/packages ./ avt-nvidia-l4t-kernel-headers 4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49 [8,166 kB]
Fetched 7,448 kB in 1s (9,397 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 180574 files and directories currently installed.)
Removing nvidia-l4t-bootloader (32.7.1-20220219090432) ...
Removing nvidia-l4t-jetson-io (32.7.1-20220219090432) ...
Removing nvidia-l4t-kernel-dtbs (4.9.253-tegra-32.7.1-20220219090432) ...
Removing nvidia-l4t-kernel-headers (4.9.253-tegra-32.7.1-20220219090432) ...
Removing nvidia-l4t-kernel (4.9.253-tegra-32.7.1-20220219090432) ...
(Reading database ... 163301 files and directories currently installed.)
Preparing to unpack .../0-nvidia-l4t-initrd_32.7.2-20220420143418_arm64.deb ...
Unpacking nvidia-l4t-initrd (32.7.2-20220420143418) over (32.7.1-20220219090432) ...
Preparing to unpack .../1-nvidia-l4t-xusb-firmware_32.7.2-20220420143418_arm64.deb ...
Unpacking nvidia-l4t-xusb-firmware (32.7.2-20220420143418) over (32.7.1-20220219090432) ...
Preparing to unpack .../2-nvidia-l4t-tools_32.7.2-20220420143418_arm64.deb ...
Unpacking nvidia-l4t-tools (32.7.2-20220420143418) over (32.7.1-20220219090432) ...
Selecting previously unselected package avt-nvidia-l4t-bootloader.
Preparing to unpack .../3-avt-nvidia-l4t-bootloader_32.7.1-4.0.0~gc3fa7ac49_arm64.deb ...
Unpacking avt-nvidia-l4t-bootloader (32.7.1-4.0.0~gc3fa7ac49) ...
Selecting previously unselected package avt-nvidia-l4t-kernel.
Preparing to unpack .../4-avt-nvidia-l4t-kernel_4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49_arm64.deb ...
Unpacking avt-nvidia-l4t-kernel (4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49) ...
Selecting previously unselected package avt-nvidia-l4t-kernel-dtbs.
Preparing to unpack .../5-avt-nvidia-l4t-kernel-dtbs_4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49_arm64.deb ...
Unpacking avt-nvidia-l4t-kernel-dtbs (4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49) ...
Selecting previously unselected package avt-nvidia-l4t-kernel-headers.
Preparing to unpack .../6-avt-nvidia-l4t-kernel-headers_4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49_arm64.deb ...
Unpacking avt-nvidia-l4t-kernel-headers (4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49) ...
Setting up nvidia-l4t-tools (32.7.2-20220420143418) ...
Setting up avt-nvidia-l4t-bootloader (32.7.1-4.0.0~gc3fa7ac49) ...
Traceback (most recent call last):
  File "/var/lib/dpkg/info/avt-nvidia-l4t-bootloader.config", line 307, in <module>
    main()
  File "/var/lib/dpkg/info/avt-nvidia-l4t-bootloader.config", line 292, in main
    db.subst('avt-nvidia-l4t-bootloader/target-board', 'default-board-configuration', config_list[0])
IndexError: list index out of range
dpkg: error processing package avt-nvidia-l4t-bootloader (--configure):
 installed avt-nvidia-l4t-bootloader package post-installation script subprocess returned error exit status 1
Setting up avt-nvidia-l4t-kernel (4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49) ...
3448-300-0002--1--jetson-nano-devkit-emmc-
Setting up avt-nvidia-l4t-kernel-dtbs (4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49) ...
Setting up nvidia-l4t-xusb-firmware (32.7.2-20220420143418) ...
3448-300-0002--1--jetson-nano-devkit-emmc-
Starting xusb firmware post-install procedure.
Update xusb firmware completed.
Reboot the target system for changes to take effect.
Setting up nvidia-l4t-initrd (32.7.2-20220420143418) ...
Setting up avt-nvidia-l4t-kernel-headers (4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49) ...
Processing triggers for avt-nvidia-l4t-kernel (4.9.253-tegra-32.7.1-4.0.0~gc3fa7ac49) ...
Errors were encountered while processing:
 avt-nvidia-l4t-bootloader
E: Sub-process /usr/bin/dpkg returned an error code (1)
Reboot now (y/n)? n
```  
At a glance, it seems like there is some issue with the bootloader.config file, though I'm not sure how to interpret this. I have used a prior release of the Allied Vision camera drivers (version 2.0.0) on this same device, running JetPack 4.5.1, and I have not seen this before.   

Any insights or assistance in installing this latest release for JetPack 4.6.1 would be greatly appreciated.

**Comment by DanielZim** [comment]
We face the same problem that the TO described. Would greatly appreciate any support!

**Comment by r0l1** [comment]
Facing the same issue:

```
Setting up avt-nvidia-l4t-kernel-headers (5.10.65-tegra-34.1.1-5.0.1~beta1~gb0feb54753) ...
Setting up avt-nvidia-l4t-bootloader (34.1.1-5.0.1~beta1~gb0feb54753) ...
^[[ATraceback (most recent call last):
  File "/var/lib/dpkg/info/avt-nvidia-l4t-bootloader.config", line 288, in <module>
    main()
  File "/var/lib/dpkg/info/avt-nvidia-l4t-bootloader.config", line 283, in main
    active_board.update_active_configuration(i)
  File "/var/lib/dpkg/info/avt-nvidia-l4t-bootloader.config", line 146, in update_active_configuration
    shutil.copyfile('/boot/%s' % new_config.dtb, '/boot/kernel_%s' % new_config.dtb)
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/boot/tegra194-p3668-0001-p3509-0000-avt.dtb'
dpkg: error processing package avt-nvidia-l4t-bootloader (--configure):
 installed avt-nvidia-l4t-bootloader package post-installation script subprocess returned error exit status 1
Setting up avt-nvidia-l4t-kernel-dtbs (5.10.65-tegra-34.1.1-5.0.1~beta1~gb0feb54753) ...
Processing triggers for avt-nvidia-l4t-kernel (5.10.65-tegra-34.1.1-5.0.1~beta1~gb0feb54753) ...
Errors were encountered while processing:
 avt-nvidia-l4t-bootloader
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by r0l1** [comment]
I found the error. The `https://github.com/alliedvision/linux_nvidia_jetson/blob/master/hardware/nvidia/platform/t19x/jakku/kernel-dts/Makefile` is missing one line:

```
dtb-$(BUILD_ENABLE) += tegra194-p3668-0001-p3509-0000-avt.dtb
```
